### PR TITLE
Router v3

### PR DESCRIPTION
**Pull request by sunmoon11100**

### CODE REVIEW

**Comment by sunmoon11100** [comment]
How about including all math functions with overflow checking in math_v2 so that everyone can clearly understand all of its functions?
The math module is only used in the router, so I think we can completely move it into math_v2.

**Comment by borispovod** [comment]
@sunmoon11100 i don't think it's good idea as it's also much more code to test/verify/audit, this why i keep only new functions.

**Comment by borispovod** [comment]
Published as optional router v3 in [branch](https://github.com/pontem-network/liquidswap/tree/router-v3) and updated docs [with it](https://docs.liquidswap.com/smart-contracts#optional-routers).

**Comment by borispovod** [comment]
So closing for now as we keep it's changes optional.

**Pull request closed without merging**
